### ISSUE TITLE
Does not appear on iPad

### ISSUE THREAD

**Issue by johan-sellstrom** [DanBurkhardt/DriverKitUserClientSample#1] opened 2024-07-18 18:52 UTC
This project builds fine but the driver does not show up on the iPad to be enabled. What am I missing?

**Comment by tolszak** [comment] 2024-08-07 15:34
> This project builds fine but the driver does not show up on the iPad to be enabled. What am I missing?

Hey, I've spent 2 or 3 days trying to run null driver on ipad. Then seems Dan was pioneer here. All looks OK except my ipad doesn't have drivers list, not the list is shown when setting button is clicked from the app :-)

Any idea how to make it work?

**Comment by tolszak** [comment] 2024-08-09 08:22
@DanBurkhardt I'm sorry for bothering so much on apple forum and here. But...


I've seen that you did great job with making the example work. Any idea how to run in on ios 17? It compiles installs but there is not driver list in main settings nor in settings bundle. Am I missing something?

**Comment by DanBurkhardt** [comment] 2024-08-09 20:39
Hey folks-- apologies, I saw this message and forgot to respond.

A few things by topic:

## Compatibility

- DriverKit is only supported on M-Series iPads (M1/M2/M3)
- Min supported version of iPadOS is iPadOS 16

## Required Settings

- If you do not have an entitlement from Apple to develop a DriverKit driver, I *think* that your iPadOS device may not be able to install one.
    - I do have one, so I actually am not sure how I would confirm whether or not this is your issue because I think my account will always be allowed to use DriverKit
    - Follow [Apple Support instructions](https://developer.apple.com/documentation/driverkit/requesting_entitlements_for_driverkit_development?language=objc) to request a DriverKit driver for your application (note: they denied me the first time I requested, but my 2nd request with more evidence and justification details was approved after a few days/weeks) 
- Your device must be in [developer mode ](https://developer.apple.com/documentation/xcode/enabling-developer-mode-on-a-device)
- You absolutely have to follow the (poorly documented) bundle id settings for the driver, as demonstrated in the example project 
    - this is going to be the cause of **most** issues where the driver is never installed or present in the bundle
    - ensure you follow the scheme as so:
        - app:     myapp.developeracct.com
        - driver: driver.myapp.developeracct.com

## Support Needs

If you are sure you have met all of the previous config and compatibility requirements, please send me the following:

- A link to your fork or to a eparate repository containing the project you are having trouble with
    - This is by far the most helpful thing for me to look at, and would help me confirm if it is a local issue or configuration issue
- Your device specs for:
    - Development machine: (OS version, Xcode version, Swift version) 
    - iPad (OS version, model number or processor type)

**Comment by tolszak** [comment] 2024-08-12 09:37
> * myapp.developeracct.com

Hello Dan,
Hats off for this repo, it will save other folks a lot of time...

Hmm you used reverse domain schema as suggested in README.
com.gigabitelabs.userclient.app.driver.dext

Please see the commit:
https://github.com/DanBurkhardt/DriverKitUserClientSample/commit/62f7d0cee5999a9b5a0b5b66c07e3aaff05e4790

The project builds, and I can deploy the ipad app as well as driver using run button from XCode.

I build on:
1. Mac Mini M1 with 14.4.1
2. Xcode - version 15.0 (15A240d)

And deploy to Ipad Mini 6th generation which seems to have A15 Bionic chip. I couldn't find any information about limits of using Driver Kit on ipad. I thought only iPadOS 17+ is requirement... If that's the case then this information is priceless. Could you please confirm that?

Thanks in advance!

**Comment by DanBurkhardt** [comment] 2024-08-15 05:09
Ah-- yes you're right I remembered it in reverse as I wasn't at my machine at the time, your bundleID scheme looks right.

And no problem, I got past the config and realized my implementation was worth sharing to save time!

Unfortunately, the issue is you have an iPad with an A15 chip and not an M-series iPad. DriverKit is only supported on iPads with M-Series chips, it's a hard limitation and will never appear in settings or install via app unless the target device has an M-series chip. I do think this requirement is covered by Apple in the very latest DriverKit WWDC session.

CC: @tolszak @johan-sellstrom

**Comment by DanBurkhardt** [comment] 2024-08-30 03:06
Closing since no further comment and confirmation of attempt to run on unsupported device. Lmk if anything else pops up.

**Closed as completed** 2024-08-30 03:07 UTC

**Comment by tolszak** [comment] 2024-09-11 11:21
Hey I'm sorry for not replying it. It stick somewhere in my mailbox. I would like to thank you very much for this repo. It saved me a lot of time!

Thank you!

**Comment by mpiffari** [comment] 2026-06-03 07:56
Hi everybody, Hi @DanBurkhardt 
I would like to ask if there are any updates on this
